print("Enter word of your school motto,one by one")
w1=input("Enter word1:")
w2=input("Enter word2:")
w3=input("Enter word3:")
w4=input("Enter word4:")
motto=" ".join([w1,w2,w3,w4])
print("Enter your school's foundation day")
dd=input("Enter dd:")
mm=input("Enter mm:")
yyyy=input("enter yyyy")
dt="/".join([dd,mm,yyyy])
print("School motto:",motto)
print("School foundation date:",dt)
