n = input("Enter name of student: ")
c = int(input("Enter class of student: "))
a = int(input("Enter age of student: "))
print("Name:", n, " Class:", c, " Age:", a)
print()
print()
print("Name:", n)
print("Class:", c)
print("Age:", a)
